#pragma once

#define LV_CONF_H 1

#define LV_CONF_INCLUDE_SIMPLE 1

#define LV_COLOR_DEPTH 16
#define LV_USE_LOG 1
#define LV_TICK_CUSTOM 1
#define LV_TICK_CUSTOM_INCLUDE "Arduino.h"
#define LV_TICK_CUSTOM_SYS_TIME_EXPR (millis())

#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_18 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1

#define LV_USE_FLEX 1
#define LV_USE_TABVIEW 1
#define LV_USE_LIST 1
#define LV_USE_DROPDOWN 1
#define LV_USE_TEXTAREA 1
#define LV_USE_KEYBOARD 1
#define LV_USE_ARC 1
#define LV_USE_BAR 1
#define LV_USE_SPINNER 1
#define LV_USE_BTN 1
#define LV_USE_LABEL 1
#define LV_USE_CANVAS 1
